name: 'Terragrunt GitHub Actions'
description: 'Runs Terragrunt commands via GitHub Actions.'
author:  'HashiCorp, Inc. Terraform Team <terraform@hashicorp.com>'
branding:
  icon: 'cloud'
  color: 'purple'
inputs:
  path-to-hcl:
    description: 'Terragrunt working directory.'
    default: '.'
runs:
  using: 'node12'
  main: 'terragrunt-plan.js'