name: 'Terragrunt Command'
description: 'Run Terragrunt With Input Command'
inputs:
  path-to-hcl:  # id of input
    description: 'Path where run terragrunt'
    required: true
    default: '.'
outputs:
  full-output: # id of output
    description: 'File with full terragrun output'
runs:
  using: 'node12'
  main: 'terragrunt-plan.js'